In [1]:
from generator import precompute_data, get_dataloader, PotentialType
from pathlib import Path

In [2]:
dx = 0.01
dy = 0.01



data_dir = Path.cwd() / "data"
# Ensure the directory exists
data_dir.mkdir(parents=True, exist_ok=True)

## Testing Data

### Generate and Save to File

In [3]:
# Precompute and Save
num_samples = 20000
file_1 = data_dir / "testing_data.npz"
# precompute_data(file_1, num_samples, dx, dy, PotentialType.ANHARMONIC)

### Test DataLoader

In [4]:
# Load DataLoader
batch_size = 1
dataloader_1 = get_dataloader(file_1, batch_size)

for batch_potentials, batch_eigenvalues, batch_labels in dataloader_1:
    print(batch_potentials.shape, batch_eigenvalues.shape, batch_labels.shape)
    print(batch_labels)
    break

torch.Size([1, 64, 64]) torch.Size([1, 2]) torch.Size([1])
tensor([2])


## Training Data

### Generate

In [5]:
# Precompute and Save
harmonic_ratio = 0.5
num_samples = 80000
file_2 = data_dir / "training_data.npz"
# precompute_data(file_2, num_samples, dx, dy, PotentialType.HARMONIC, mix_ratio=harmonic_ratio)



### Test DataLoader

In [6]:
# Load DataLoader
batch_size = 256
dataloader_2 = get_dataloader(file_2, batch_size, balance_batches=True, harmonic_ratio=harmonic_ratio)

In [7]:
for batch_potentials, batch_eigenvalues, batch_labels in dataloader_2:
    print(batch_potentials.shape, batch_eigenvalues.shape, batch_labels.shape)
    print(batch_labels)
    # break

torch.Size([256, 64, 64]) torch.Size([256, 2]) torch.Size([256])
tensor([0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
        1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
        1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
        1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
        1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
        1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
        0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
        0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
        1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
        1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1])
torch.Size([256, 64, 64]) torch.Size([256, 2]) torch.Size([256])
tensor([1, 1,